import type { NextPage } from 'next'
import Head from 'next/head'
import navStyle from '../styles/navStyles.module.css'
import indexStyle from '../styles/indexStyle.module.css'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pagrindinis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={indexStyle.main}>

        <nav className={navStyle.navigation}>
          <div>
            <h1>Fit<span>ness</span></h1> 
          </div>

          <ul>
            <li><a href="/">Pagrindinis</a></li>
            <li><a href="Schedule">Tvarkaraščiai</a></li>
            <li><a href="Programs">Treniruočių programos</a></li>
            <li><a href="contact">Kontaktai</a></li>
            <li><a href="register">Registracija</a></li>
            <li><a href="login">Prisijungti</a></li>
          </ul>
        </nav>

        <div className={indexStyle.header}>
          <h1>SPORTO KLUBAS FITNESS</h1>
        </div>
        
        <div className={indexStyle.buttons}>
          <div>
            <a href="schedules" className={indexStyle.button1}>
              <h1>Tvarkaraščiai</h1>
            </a>

            <a href="programs" className={indexStyle.button2}>
              <h1>Treniruočių programos</h1>
            </a>
          </div>
        </div>
      </main> 
    </div>
  )
}
export default Home
