import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import navStyle from '../styles/navStyles.module.css'
import mainStyle from '../styles/programsStyle.module.css'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Treniruočių programos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={mainStyle.main}>

        <nav className={navStyle.navigation}>
          <div>
            <h1>Fit<span>ness</span></h1>
          </div>

          <ul>
            <li><a href="/">Pagrindinis</a></li>
            <li><a href="schedules">Tvarkaraščiai</a></li>
            <li><a href="">Treniruočių programos</a></li>
            <li><a href="contact">Kontaktai</a></li>
            <li><a href="register">Registracija</a></li>
            <li><a href="login">Prisijungti</a></li>
          </ul>
        </nav>

        <div>
          <h1>Treniruočių programos</h1>

          <div>
              <p>Aerobika</p>
              <p>bubribiuiuiuebvbviuebviuebrviuebivberivb</p>
          </div>

          <div>
              <p>Pilatės treniruotė</p>
              <p>beribiuvivbieruvberiubviuerbviuebiuberivberivb</p>
          </div>

          <div>
              <p>Bokso treniruotė</p>
              <p>momgnfownoinongoengoerngerngerngonerogner</p>
          </div>

          <div>
              <p>Sunkiojo atletika</p>
              <p>ifiurbgiuiuebierbgierbgiebierbgierbgiuebgeiurgbiu</p>
          </div>
        </div>

      </main> 
    </div>
  )
}
export default Home
