import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import navStyle from '../styles/navStyles.module.css'
import mainStyle from '../styles/scheduleStyle.module.css'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tvarkaraščiai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={mainStyle.main}>

        <nav className={navStyle.navigation}>
          <div>
            <h1>Fit<span>ness</span></h1>
          </div>

          <ul>
            <li><a href="/">Pagrindinis</a></li>
            <li><a href="">Tvarkaraščiai</a></li>
            <li><a href="programs">Treniruočių programos</a></li>
            <li><a href="contact">Kontaktai</a></li>
            <li><a href="register">Registracija</a></li>
            <li><a href="login">Prisijungti</a></li>
          </ul>
        </nav>

        
      </main> 
    </div>
  )
}
export default Home
