import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { IWorker } from '../interface/IWorker'
import navStyle from '../styles/navStyles.module.css'
import mainStyle from '../styles/scheduleStyle.module.css'
const workers = () => {
  const [worker, setWorker] = useState<Array<IWorker>>([])

  const restApi = "http://127.0.0.1:8000/api"

  const getWorker = async () => {
    let worker: Array<IWorker> = await fetch(restApi+'/darbuotojas').then(r => r.json())
    setWorker(worker)
  }

  const postWorker = async () => {
    window.location.href = 'addWorker'
  }

  function updateWorker(id: number)
  {
    window.location.href = `updateWorker?ID=${id}`;
  }

  async function deleteWorker(id: number)
  {
    debugger
    await axios.delete(`${restApi}/darbuotojas/${id}`).then(function (response) {
      console.log(response);
    })
      .catch(function (error) {
        console.log(error);
      });
  }
  
  useEffect(() => {
    getWorker();
  }, []);

  return (
    <div>
      <Head>
        <title>Darbuotojai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={mainStyle.main}>

        <nav className={navStyle.navigation}>
          <div>
            <h1>Fit<span>ness</span></h1>
          </div>

          <ul>
            <li><a href="/">Pagrindinis</a></li>
            <li><a href="">Tvarkaraščiai</a></li>
            <li><a href="Programs">Treniruočių programos</a></li>
            <li><a href="contact">Kontaktai</a></li>
            <li><a href="register">Registracija</a></li>
            <li><a href="login">Prisijungti</a></li>
          </ul>
        </nav>
        
        <h1>Darbuotojai</h1>

        <button onClick={postWorker}>
          Pridėti
        </button>

        {worker !== undefined? 
           <table className="table table-bordered">
           <tr>
               <th>Nr</th>
               <th>Asmens kodas</th>
               <th>Vardas</th>
               <th>Pavarde</th>
               <th>Slaptazodis</th>
               <th>El. paštas</th>
               <th>Darbo etatas</th>
           </tr>

           {worker.map((worker, index) => (
             <tr data-index={index}>
               <td>{worker.darbuotojo_nr}</td>
               <td>{worker.asmens_kodas}</td>
               <td>{worker.vardas}</td>
               <td>{worker.pavarde}</td>
               <td>{worker.slaptazodis}</td>
               <td>{worker.el_pastas}</td>
               <td>{worker.darbo_etatas}</td>
               <td>
                 <button onClick={() => deleteWorker(worker.darbuotojo_nr)}>
                   Šalinti
                 </button>
               </td>
               <td>
                 <button onClick={() => updateWorker(worker.darbuotojo_nr)}>
                   Redaguoti
                 </button>
               </td>
             </tr>
           ))}
 
       </table>
      :null}
      </main> 
    </div>
  )
}
export default workers